# Battery block constants

B_CAPACITY = 3
B_MAX_CHARGE_CURRENT = 5
B_MAX_DISCHARGE_CURRENT = 6
B_VOLTAGE = 8
B_CURRENT = 9
B_SOH_SOC = 10
B_CYCLE_COUNT = 11
B_MAX_CELL_TEMP = 12
B_MIN_CELL_TEMP = 13
B_MAX_CELL_VOLTAGE = 14
B_MIN_CELL_VOLTAGE = 15
B_TEMP_CELLS = 16
B_VOLTAGE_CELLS = 17
B_FIRMWARE = 18
B_SERIAL_START = 19
B_SERIAL_LEN = 14
