#
# number_types.py
#

from ..constants.hold_registers import *

NUMBER_TYPES = [
    # --- System & Grid ---
    {
        "name": "Modbus Address",
        "register": H_COM_ADDRESS,
        "min": 0,
        "max": 150,
        "step": 1,
        "unit": "",
        "multiplier": 1,
        "icon": "mdi:numeric",
        "enabled": False,
        "visible": True,
    },
    {
        "name": "Grid Connect Time",
        "register": H_CONNECT_TIME,
        "min": 30,
        "max": 600,
        "step": 1,
        "unit": "s",
        "multiplier": 1,
        "icon": "mdi:timer-sand",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Grid Reconnect Time",
        "register": H_RECONNECT_TIME,
        "min": 0,
        "max": 900,
        "step": 1,
        "unit": "s",
        "multiplier": 1,
        "icon": "mdi:timer-refresh",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Grid Voltage Low Limit",
        "register": H_GRID_VOLT_CONN_LOW,
        "min": 0.0,
        "max": 6553.5,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:arrow-collapse-vertical",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Grid Voltage High Limit",
        "register": H_GRID_VOLT_CONN_HIGH,
        "min": 0.0,
        "max": 6553.5,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:arrow-expand-vertical",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Grid Frequency Low Limit",
        "register": H_GRID_FREQ_CONN_LOW,
        "min": 0.00,
        "max": 655.35,
        "step": 0.01,
        "unit": "Hz",
        "multiplier": 100,
        "icon": "mdi:arrow-collapse-horizontal",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Grid Frequency High Limit",
        "register": H_GRID_FREQ_CONN_HIGH,
        "min": 0.00,
        "max": 655.35,
        "step": 0.01,
        "unit": "Hz",
        "multiplier": 100,
        "icon": "mdi:arrow-expand-horizontal",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Max Grid Input Power",
        "register": H_MAX_GRID_INPUT_POWER,
        "min": 0,
        "max": 65535,
        "step": 1,
        "unit": "W",
        "multiplier": 1,
        "icon": "mdi:import",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "External CT Power Offset",
        "register": H_WCT_POWER_OFFSET,
        "min": -32768, # signed short int
        "max": 32767,
        "step": 1,
        "unit": "W",
        "multiplier": 1,
        "icon": "mdi:plus-minus-variant",
        "enabled": True,
        "visible": True,
    },

    # --- Power Control ---
    {
        "name": "Active Power Percent",
        "register": H_ACTIVE_POWER_PERCENT_CMD,
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:brightness-percent",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Power Soft Start Slope",
        "register": H_POWER_SOFT_START_SLOPE,
        "min": 1,
        "max": 4000,
        "step": 1,
        "unit": "%/min",
        "multiplier": 1,
        "icon": "mdi:stairs-up",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Max Backflow Power",
        "register": H_MAX_BACKFLOW_POWER,
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:export",
        "enabled": True,
        "visible": True,
    },

    # --- Charging & Discharging ---
    {
        "name": "Charge Current",
        "register": H_CHARGE_CURRENT,
        "min": 0,
        "max": 500,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Discharge Current",
        "register": H_DISCHARGE_CURRENT,
        "min": 0,
        "max": 500,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "AC Charge Power",
        "register": H_AC_CHARGE_POWER_CMD,
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-charging",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "AC Charge SOC Limit",
        "register": H_AC_CHARGE_SOC_LIMIT,
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-charging-90",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "AC Charge Start Voltage",
        "register": H_AC_CHARGE_START_VOLT,
        "min": 38.5,
        "max": 52.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-arrow-up-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "AC Charge End Voltage",
        "register": H_AC_CHARGE_END_VOLT,
        "min": 48.0,
        "max": 59.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-check-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "AC Charge Start SOC",
        "register": H_AC_CHARGE_START_SOC,
        "min": 0,
        "max": 90,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-arrow-up-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "AC Charge Current from Grid",
        "register": H_AC_CHARGE_BAT_CURRENT,
        "min": 0,
        "max": 140,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "On-Grid Cut-Off SOC",
        "register": H_EOD_SOC,
        "min": 10,
        "max": 90,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-low",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "On-Grid Cut-Off Voltage",
        "register": H_ONGRID_EOD_VOLTAGE,
        "min": 40.0,
        "max": 56.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:grid",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Stop Charging SOC",
        "register": H_BAT_STOP_CHARGE_SOC,
        "min": 10,
        "max": 101,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-off",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Stop Charging Voltage",
        "register": H_BAT_STOP_CHARGE_VOLT,
        "min": 40.0,
        "max": 59.5,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-off-outline",
        "enabled": True,
        "visible": True,
    },

    # --- EPS (Off-Grid) ---
    {
        "name": "EPS Voltage Set",
        "register": H_EPS_VOLTAGE_SET,
        "min": 208,
        "max": 277,
        "step": 1,
        "unit": "V",
        "multiplier": 1,
        "icon": "mdi:power-socket-us",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "EPS Frequency Set",
        "register": H_EPS_FREQ_SET,
        "min": 50,
        "max": 60,
        "step": 1,
        "unit": "Hz",
        "multiplier": 1,
        "icon": "mdi:sine-wave",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Off-Grid Cut-Off SOC",
        "register": H_SOC_LOW_LIMIT_FOR_EPS_DISCHG,
        "min": 0,
        "max": 100, # Range is 0-EOD, setting to 100 for max flexibility
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-alert",
        "enabled": True,
        "visible": True,
    },

    # --- Unmatched/Lead-Acid Battery ---
    {
        "name": "Unmatched Battery Capacity",
        "register": H_BATTERY_CAPACITY,
        "min": 0,
        "max": 10000,
        "step": 1,
        "unit": "Ah",
        "multiplier": 1,
        "icon": "mdi:battery",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Unmatched Battery Nominal Voltage",
        "register": H_BATTERY_NOMINAL_VOLTAGE,
        "min": 40.0,
        "max": 59.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Float Charge Voltage",
        "register": H_FLOAT_CHARGE_VOLT,
        "min": 50.0,
        "max": 56.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-plus-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Equalization Interval",
        "register": H_EQUALIZATION_INTERVAL,
        "min": 0,
        "max": 365,
        "step": 1,
        "unit": "Days",
        "multiplier": 1,
        "icon": "mdi:calendar-sync",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Equalization Time",
        "register": H_EQUALIZATION_TIME,
        "min": 0,
        "max": 24,
        "step": 1,
        "unit": "Hours",
        "multiplier": 1,
        "icon": "mdi:timer-cog",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Low Voltage Alarm",
        "register": H_BAT_LOW_VOLTAGE_ALARM,
        "min": 40.0,
        "max": 50.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-alert-variant-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Low Voltage Recovery",
        "register": H_BAT_LOW_BACK_VOLTAGE,
        "min": 42.0,
        "max": 52.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:battery-sync-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Low SOC Alarm",
        "register": H_BAT_LOW_SOC_ALARM,
        "min": 0,
        "max": 90,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-alert-variant-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Low SOC Recovery",
        "register": H_BAT_LOW_BACK_SOC,
        "min": 20,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:battery-sync-outline",
        "enabled": True,
        "visible": True,
    },

    # --- Generator ---
    {
        "name": "Generator Rated Power",
        "register": H_GEN_RATED_POWER,
        "min": 0,
        "max": 65535,
        "step": 1,
        "unit": "W",
        "multiplier": 1,
        "icon": "mdi:engine",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Generator Charge Start Voltage",
        "register": H_GEN_CHARGE_START_VOLT,
        "min": 38.4,
        "max": 52.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:engine-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Generator Charge End Voltage",
        "register": H_GEN_CHARGE_END_VOLT,
        "min": 48.0,
        "max": 59.0,
        "step": 0.1,
        "unit": "V",
        "multiplier": 10,
        "icon": "mdi:engine-off-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Generator Charge Start SOC",
        "register": H_GEN_CHARGE_START_SOC,
        "min": 0,
        "max": 90,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:engine-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Generator Charge End SOC",
        "register": H_GEN_CHARGE_END_SOC,
        "min": 20,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:engine-off-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Max Generator Charge Current",
        "register": H_MAX_GEN_CHARGE_BAT_CURRENT,
        "min": 0,
        "max": 4000,
        "step": 1,
        "unit": "A",
        "multiplier": 1,
        "icon": "mdi:engine",
        "enabled": True,
        "visible": True,
    },

    # --- Peak Shaving ---
    {
        "name": "Grid Peak Shaving Power",
        "register": H_GRID_PEAK_SHAVING_POWER,
        "min": 0.0,
        "max": 25.5,
        "step": 0.1,
        "unit": "kW",
        "multiplier": 10,
        "icon": "mdi:chart-gantt",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Grid Peak Shaving SOC",
        "register": H_GRID_PEAK_SHAVING_SOC,
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "multiplier": 1,
        "icon": "mdi:chart-gantt",
        "enabled": True,
        "visible": True,
    },

    # --- Miscellaneous ---
    {
        "name": "LCD Password",
        "register": H_LCD_PASSWORD,
        "min": 0,
        "max": 65535,
        "step": 1,
        "unit": "",
        "multiplier": 1,
        "icon": "mdi:lock",
        "enabled": False,
        "visible": True,
    },
]