from ..constants.hold_registers import *
from ..utils import get_bits, set_bits

SELECTBOX_TYPES = [
    {
        "name": "AC Charge Type",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 1, 3),
        "compose": lambda orig, value: set_bits(orig, 1, 3, value),
        "options": {
            0: "Disable",
            1: "According to Time",
            2: "According to Voltage",
            3: "According to SOC",
            4: "According to Voltage and Time",
            5: "According to SOC and Time",
        },
        "icon": "mdi:battery-charging",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Other",
    },
    {
        "name": "Discharge Control Type",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 4, 2),
        "compose": lambda orig, value: set_bits(orig, 4, 2, value),
        "options": {
            0: "According to Voltage",
            1: "According to SOC",
            2: "According to Both",
        },
        "icon": "mdi:battery-arrow-down",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Other",
    },
    {
        "name": "On-Grid EOD Type",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 6, 1),
        "compose": lambda orig, value: set_bits(orig, 6, 1, value),
        "options": {
            0: "According to Voltage",
            1: "According to SOC",
        },
        "icon": "mdi:grid",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Generator Charge Type",
        "register": H_SYSTEM_ENABLE_2,   # 120
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 7, 1),
        "compose": lambda orig, value: set_bits(orig, 7, 1, value),
        "options": {
            0: "According to Battery Voltage",
            1: "According to Battery SOC",
        },
        "icon": "mdi:engine",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Generator",
    },
    {
        "name": "System Type",
        "register": H_SET_SYSTEM_TYPE,    # 112
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "No parallel (single one)",
            1: "Single-phase parallel (primary)",
            2: "Secondary",
            3: "Three phase parallel (Master)",
            4: "2*208 (Master) - for split-phase",
        },
        "icon": "mdi:vector-link",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Other",
    },
    {
        "name": "Language",
        "register": H_LANGUAGE_AND_DEVICE_TYPE, # 16
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "English",
            1: "German",
        },
        "icon": "mdi:translate",
        "enabled": False,
        "visible": True,
        "master_only": True,
        "device_group": "Other",
    },
    {
        "name": "PV Input Model",
        "register": H_PV_INPUT_MODEL, # 20
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "No PV",
            1: "PV1 in",
            2: "PV2 in",
            3: "PV3 in",
            4: "PV1 & PV2 in",
            5: "PV1 & PV3 in",
            6: "PV2 & PV3 in",
            7: "PV1 & PV2 & PV3 in",
        },
        "icon": "mdi:solar-panel",
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "PV",
    },
    {
        "name": "Reactive Power Command Type",
        "register": H_REACTIVE_POWER_CMD_TYPE, # 59
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "Unit power factor",
            1: "Fixed PF",
            2: "Default PF curve (Q(P))",
            3: "Custom PF curve",
            4: "Capacitive reactive power percentage",
            5: "Inductive reactive power percentage",
            6: "Q(V) curve",
            7: "Q(V) Dynamic",
        },
        "icon": "mdi:flash",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Output Priority Config",
        "register": H_OUTPUT_PRIORITY_CONFIG, # 145
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "Battery First",
            1: "PV First",
            2: "AC First",
        },
        "icon": "mdi:power-plug",
        "enabled": False,
        "visible": True,
        "master_only": True,
        "device_group": "Other",
    },
    {
        "name": "Line Mode",
        "register": H_LINE_MODE, # 146
        "register_type": "hold",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            0: "APL (Appliance)",
            1: "UPS (Uninterruptible Power Supply)",
            2: "GEN (Generator)",
        },
        "icon": "mdi:power-settings",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Other",
    },
    {
        "name": "Grid Type",
        "register": H_GRID_TYPE, # 205
        "register_type": "hold",
        "icon": "mdi:transmission-tower",
        "extract": lambda reg: reg,
        "compose": lambda orig, value: value,
        "options": {
            # Standard Types
            0: "Split Phase 240V/120V",
            1: "3-Phase Star 120V/208V",
            2: "Single Phase 240V",
            3: "Single Phase 230V",
            4: "Split Phase 200V/100V",
            # New Three-Phase Types
            5: "3-Phase Delta 230V/230V",
            6: "3-Phase Star 240V/415V",
            7: "3-Phase Star 230V/400V",
            8: "3-Phase Star 220V/380V"
        },
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Working Mode",
        "register": H_FUNCTION_ENABLE_1, # 21
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 9, 1),
        "compose": lambda orig, value: set_bits(orig, 9, 1, value),
        "options": {
            0: "Standby",
            1: "Normal",
        },
        "icon": "mdi:power-settings",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Settings & Schedules",
    },
    {
        "name": "Smart Load Enable",
        "register": H_FUNCTION_ENABLE_4, # 179
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 13, 1),
        "compose": lambda orig, value: set_bits(orig, 13, 1, value),
        "options": {
            0: "Generator",
            1: "Smart Load",
        },
        "icon": "mdi:home-lightning-bolt",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Other",
    },
    {
        "name": "LCD Screen Type",
        "register": H_LCD_CONFIG, # 224
        "register_type": "hold",
        "extract": lambda reg: get_bits(reg, 8, 1),
        "compose": lambda orig, value: set_bits(orig, 8, 1, value),
        "options": {
            0: "Screen 'B' size",
            1: "Screen 'S' size",
        },
        "icon": "mdi:monitor",
        "enabled": False,
        "visible": True,
        "master_only": True,
        "device_group": "Other",
    },
    {
        "name": "EPS Voltage Set",
        "register": H_EPS_VOLTAGE_SET,
        "register_type": "hold",
        "icon": "mdi:power-socket-us",
        "extract": lambda value: value,
        "compose": lambda orig, value: value,
        "options": {
            208: "208 V",
            220: "220 V",
            230: "230 V",
            240: "240 V",
            277: "277 V"
        },
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "EPS",
    },
    {
        "name": "EPS Frequency Set",
        "register": H_EPS_FREQ_SET,
        "register_type": "hold",
        "icon": "mdi:sine-wave",
        "extract": lambda value: value,
        "compose": lambda orig, value: value,
        "options": {
            50: "50 Hz",
            60: "60 Hz"
        },
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "EPS",
    },
    {
        "name": "Off-grid Composed Phase",
        "register": H_SET_COMPOSED_PHASE,
        "register_type": "hold",
        "icon": "mdi:chart-timeline-variant",
        "extract": lambda value: value & 0xFF,
        "compose": lambda orig, value: value,
        "options": {
            1: "R Phase",
            2: "S Phase",
            3: "T Phase"
        },
        "enabled": True,
        "visible": True,
        "master_only": False,
        "device_group": "Grid",
    },
]