#
# entity_descriptions/sensor_types.py
#

from ..constants.input_registers import *
from ..const import CONF_RATED_POWER

SENSOR_TYPES = [
    # --- Calc  Sensors ---
    {
        "name": "Load Percentage",
        "register_type": "calculated",         # Special type to trigger new logic
        "depends_on": [I_STATE, I_PLOAD, I_PEPS], # Registers this sensor depends on
        "unit": "%",
        "device_class": "power_factor", # Or None, as % isn't a standard class
        "icon": "mdi:gauge",
        "enabled": True,
        "visible": True,
        "extract": lambda registers, entry: (
            (
                round((registers.get(I_PLOAD, 0) / rated_power) * 100, 2)
                if registers.get(I_STATE) == 16
                else round((registers.get(I_PEPS, 0) / rated_power) * 100, 2)
                if registers.get(I_STATE) == 64
                else 0
            ) if (rated_power := entry.data.get(CONF_RATED_POWER)) and rated_power > 0 else 0
        )
    },
    # --- State Sensors ---
    {
        "name": "Inverter State",
        "register": I_STATE,
        "register_type": "input",
        "extract": lambda value: value,
        "icon": "mdi:state-machine",
        "enabled": True,
        "visible": True,
        "default": "Unknown State",
        "options": {
            0: "Standby",
            1: "Fault",
            2: "Programming / Updating",
            4: "PV Powering Load - Surplus Exporting to Grid",
            8: "PV Powering Load & Charging Battery",
            12: "PV Powering Load, Charging Battery & Exporting to Grid",
            16: "Battery Discharging to Load - Surplus Exporting to Grid",
            20: "PV & Battery Powering Load - Surplus Exporting to Grid",
            32: "Grid Charging Battery",
            40: "Grid & PV Charging Battery",
            64: "Off-Grid: Battery Powering Load",
            96: "Off-Grid: AC Coupled PV Charging Battery",
            128: "Off-Grid: PV Power Unstable (Prohibited)",
            136: "Off-Grid: PV Powering Load & Charging Battery",
            192: "Off-Grid: PV & Battery Powering Load",
        }
    },
    {
        "name": "Inverter State Code",
        "register": I_STATE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:numeric",
        "enabled": True,
        "visible": True, # Set to False if you only want the text version visible
    },

    # --- Core Status & PV Information ---
    {
        "name": "PV1 Voltage",
        "register": I_VPV1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "PV2 Voltage",
        "register": I_VPV2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "PV1 Power",
        "register": I_PPV1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "PV2 Power",
        "register": I_PPV2,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "PV3 Power",
        "register": I_PPV3,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Total PV Power (Calculated)",
        "depends_on": [I_PPV1, I_PPV2, I_PPV3], # Registers this sensor depends on
        "register_type": "calculated",
        "extract": lambda registers, entry: registers.get(I_PPV1, 0) + registers.get(I_PPV2, 0) + registers.get(I_PPV3, 0),
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:solar-power",
        "enabled": True,
        "visible": True,
    },

    # --- Battery Information ---
    {
        "name": "Battery Voltage",
        "register": I_VBAT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.1,
        "icon": "mdi:car-battery",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery SOC",
        "register": I_SOC_SOH,
        "register_type": "input",
        "extract": lambda value: value & 0xFF,
        "unit": "%",
        "device_class": "battery",
        "scale": 1.0,
        "icon": "mdi:battery-high",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery SOH",
        "register": I_SOC_SOH,
        "register_type": "input",
        "extract": lambda value: (value >> 8) & 0xFF,
        "unit": "%",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:battery-heart-variant",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Charge Power",
        "register": I_PCHARGE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:battery-arrow-up",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Discharge Power",
        "register": I_PDISCHARGE,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:battery-arrow-down",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Battery Temperature",
        "register": I_TBAT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "scale": 1.0,
        "icon": "mdi:thermometer",
        "enabled": True,
        "visible": True,
    },

    # --- Grid Information ---
    {
        "name": "Grid Voltage", # Assumes R-Phase or single phase
        "register": I_VAC_R,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.1,
        "icon": "mdi:transmission-tower",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Grid Frequency",
        "register": I_FAC,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Hz",
        "device_class": "frequency",
        "scale": 0.01,
        "icon": "mdi:sine-wave",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Inverter Power",
        "register": I_PINV,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "AC Charging Rectification Power",
        "register": I_PREC,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:power-plug",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Inverter Current",
        "register": I_IINV_RMS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "scale": 0.01,
        "icon": "mdi:current-ac",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Power Factor",
        "register": I_PF,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "%",
        "device_class": "power_factor",
        "scale": 0.001,
        "icon": "mdi:angle-acute",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Power to Grid",
        "register": I_PTOGRID,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-export",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Power from Grid",
        "register": I_PTOUSER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:transmission-tower-import",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Load Power",
        "register": I_PLOAD,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "On-Grid Load Power",
        "register": I_ONGRID_LOAD_POWER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:home-lightning-bolt-outline",
        "enabled": False,
        "visible": True,
    },


    # --- EPS (Off-Grid) Information ---
    {
        "name": "EPS Voltage",
        "register": I_VEPS_R,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "EPS Frequency",
        "register": I_FEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "Hz",
        "device_class": "frequency",
        "scale": 0.01,
        "icon": "mdi:sine-wave",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "EPS Power",
        "register": I_PEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "W",
        "device_class": "power",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "EPS Apparent Power",
        "register": I_SEPS,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "VA",
        "device_class": "apparent_power",
        "scale": 1.0,
        "icon": "mdi:power-plug-off",
        "enabled": True,
        "visible": True,
    },

    # --- Daily Energy ---
    {
        "name": "PV1 Energy Today",
        "register": I_EPV1_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:solar-power",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Inverter Energy Today",
        "register": I_EINV_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:power-plug",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Charge Energy Today",
        "register": I_ECHG_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-up-box",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Discharge Energy Today",
        "register": I_EDISCHG_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:battery-arrow-down-box",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "EPS Energy Today",
        "register": I_EEPS_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:power-plug-off",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Energy to Grid Today",
        "register": I_ETOGRID_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:home-export-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Energy from Grid Today",
        "register": I_ETOUSER_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:home-import-outline",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Generator Energy Today",
        "register": I_EGEN_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:engine",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Load Consumption Today",
        "register": I_ELOAD_DAY,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "kWh",
        "device_class": "energy",
        "scale": 0.1,
        "icon": "mdi:home-lightning-bolt",
        "enabled": True,
        "visible": True,
    },

    # --- System & Temperature ---
    {
        "name": "Internal Temperature",
        "register": I_TINNER,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "scale": 1.0,
        "icon": "mdi:thermometer",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "Radiator Temperature",
        "register": I_TRADIATOR1,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "scale": 1.0,
        "icon": "mdi:fan",
        "enabled": True,
        "visible": True,
    },

    # --- BMS Information ---
    {
        "name": "BMS Max Charge Current",
        "register": I_BMS_MAX_CHG_CURR,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Max Discharge Current",
        "register": I_BMS_MAX_DISCHG_CURR,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "device_class": "current",
        "scale": 0.1,
        "icon": "mdi:battery-lock",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Charge Voltage Reference",
        "register": I_BMS_CHARGE_VOLT_REF,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.1,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Discharge Cut-off Voltage",
        "register": I_BMS_DISCHG_CUT_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.1,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Battery Current",
        "register": I_BMS_BAT_CURRENT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "A",
        "extract": lambda value: value if value < 32768 else value - 65536,
        "scale": 0.1,
        "icon": "mdi:current-dc",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Max Cell Voltage",
        "register": I_BMS_MAX_CELL_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.001,
        "icon": "mdi:battery-positive",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Min Cell Voltage",
        "register": I_BMS_MIN_CELL_VOLT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.001,
        "icon": "mdi:battery-negative",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Max Cell Temperature",
        "register": I_BMS_MAX_CELL_TEMP,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "icon": "mdi:thermometer-chevron-up",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Min Cell Temperature",
        "register": I_BMS_MIN_CELL_TEMP,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "°C",
        "device_class": "temperature",
        "scale": 0.1,
        "icon": "mdi:thermometer-chevron-down",
        "enabled": True,
        "visible": True,
    },
    {
        "name": "BMS Cycle Count",
        "register": I_BMS_CYCLE_COUNT,
        "register_type": "input",
        "extract": lambda value: value,
        "unit": "cycles",
        "device_class": None,
        "scale": 1.0,
        "icon": "mdi:battery-sync",
        "enabled": True,
        "visible": True,
    },
]